export { EmailShell } from "./email-shell";
export { EmailHeader } from "./email-header";
export { JarretteHeader } from "./jarrette-header";
export { JarretteFooter } from "./jarrette-footer";
export { ProductGrid } from "./product-grid";
export type { ProductGridItem } from "./product-grid";
export { BrandStrip } from "./brand-strip";
export { TextAlertsOptIn } from "./text-alerts";
export { Logo } from "./logo";
export { SectionHeading } from "./section-heading";
export { AppBanner, AppDownloadLink } from "./app-banner";
export { AppStoreBadge } from "./app-store-badge";
export { EmailRating } from "./email-rating";
export { ForecastCard } from "./forecast-card";
export { EmailFooter } from "./email-footer";
export { EmailHero } from "./email-hero";
export { EmailSection } from "./email-section";
export { CTAButton } from "./cta-button";
export { Divider } from "./divider";
export { DetailRow } from "./detail-row";
export { BookingCard } from "./booking-card";
export type { BookingDetails } from "./booking-card";

// Phase 0 foundations — shared primitives for the new email categories.
export { Callout } from "./callout";
export type { CalloutTone } from "./callout";
export { StatusHero } from "./status-hero";
export { IdStamp } from "./id-stamp";
export type { IdStampItem } from "./id-stamp";
export { WhatChanged } from "./what-changed";
export type { FieldChange } from "./what-changed";
export { ItemizedList } from "./line-items";
export type { LineItem, LineItemGroup } from "./line-items";
export { PaymentSummary } from "./payment-summary";
export type { PaymentRow } from "./payment-summary";
export { StatusBadge } from "./status-badge";
export type { PaymentStatus } from "./status-badge";
export { GiftCardVisual } from "./gift-card-visual";
export { ContactBlock } from "./contact-block";
export type { ContactField } from "./contact-block";
export { DataTable } from "./data-table";
export type { DataColumn } from "./data-table";
export { VenueBadge } from "./venue-badge";
export { PlayerRoster } from "./player-roster";
export type { RosterPlayer } from "./player-roster";
export { PunchCard } from "./punch-card";
export { SignatureBlock } from "./signature-block";
export { PaymentMethod } from "./payment-method";
export { RedemptionCode } from "./redemption-code";
export type { RedemptionVariant } from "./redemption-code";
export { DetailCard } from "./detail-card";
export { FeatureList } from "./feature-list";
export type { FeatureItem } from "./feature-list";
export { IconBadge } from "./icon-badge";
export { LocationBlock } from "./location-block";
export { PolicyTag } from "./policy-tag";
export { Checklist } from "./checklist";
export { NumberedSteps } from "./numbered-steps";
export { SupportLine } from "./support-line";
export { CTAStack } from "./cta-stack";
export { Panel } from "./panel";
export { EmailIntro } from "./email-intro";
export { SummaryStrip } from "./summary-strip";
export type { SummaryStripItem } from "./summary-strip";
